FROM python:3.11-slim

WORKDIR /app

RUN pip install poetry==1.8.3
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && poetry install --no-root --only main --no-interaction --no-ansi

COPY . .

EXPOSE 8501
CMD ["streamlit", "run", "chatbot_frontend/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
