version: '3.8'

services:
  api:
    build:
      context: ./chatbot_api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./chatbot_frontend
    ports:
      - "8501:8501"

  portal:
    build:
      context: ./cypher_example_portal
    ports:
      - "8502:8502"
