FROM python:3.11-slim

WORKDIR /app

RUN pip install poetry
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && poetry install --without dev --no-interaction --no-ansi

COPY . .

EXPOSE 8502
CMD ["streamlit", "run", "cypher_example_portal/app.py", "--server.port", "8502", "--server.address", "0.0.0.0"]
